### PR TITLE
WhatsBot v1.0 alpha

### PR DESCRIPTION
**Pull request by fermino**
The new version of WhatsBot is ready :D
It is in alpha. It means that we have to check if everything work properly. And if it does, v1.0 will be ready!

I will make a sub-branch to add deleted modules. 

@uppaljs @saadmeman @DurtyFree @aazbeltran 

Thanks everyone for supporting!

### CODE REVIEW

**Comment by fermino** [comment]
I'm working with the modules here.

**Comment by DurtyFree** [comment]
Reeaaally nice work dude.  Keep up the good work.
I would contribute to the repo if I had the time to ._.

**Comment by fermino** [comment]
Thanks @DurtyFree :D
I'm making some tutos, how to create modules, how does it works, etc.

**Comment by fermino** [comment]
This is almost ready :D:D:D
And :D xD

**Comment by DurtyFree** [comment]
I like it :+1:

**Pull request merged**
