### PR TITLE
Cleanup as Recommended for Translation Module

### PR DESCRIPTION
**Pull request by uppaljs**
Hi,

Here's another try at this :-) I hope this time it's okay :+1: 

I have also added a readme file for details. 

Cheers!

### CODE REVIEW

**Comment by uppaljs** [comment]
Hi,

Are you going to merge this?

Thanks,

**Comment by fermino** [comment]
Oh, I didn't see the commits. Tomorrow I'll test it. I can't do it today :/

**Comment by fermino** [comment]
Please, register in http://whatsbot.org, and create posts in /Development/Modules (Subforum) :)

**Comment by fermino** [comment]
!exchange added <https://github.com/fermino/WhatsBot/commit/4a06675f9134709e273f6a77809b27e9a3920f7a>

**Pull request closed without merging**
